empleado/applications/departamento/urls.py
from django.urls import path, include
from . import views

app_name = 'departamento_app'
urlpatterns = [
    #----------------- URLS DE MI PRIMER PROYECTO --------------------------------------------------------------------------------------------------------------   
    path('', 
        views.DepartamentosListView.as_view(),
        name= 'ListarDepartamentos'
    ),
    path('agregarDepartamento/',
          views.departamentoFormView.as_view(),
            name= 'addDepartamento' ),
    
    #----------------- URLS DE PRUEBAS --------------------------------------------------------------------------------------------------------------
    path('index/', views.indexView.as_view() ),
    
]

empleado/applications/persona/urls.py
from django.urls import path
from . import views

app_name = 'persona_app'


urlpatterns = [
 #----------------- URLS DE MI PRIMER PROYECTO --------------------------------------------------------------------------------------------------------------   
     path('/', 
         views.inicio.as_view(),
         name= 'inicio'
    ),
     path('allViews/',
           views.AllViews.as_view(),
           name= 'listarEmpleados'
     ),
     path('detalles_empleado/<int:pk>',
           views.DetailViewEmpleado.as_view(),
           name= 'detalles_empleado'
     ),
     path('AllViewsByArea/<shortName>/', 
          views.AllViewsByArea.as_view(),
          name='EmpleadosPorArea'
     ),
     path('allViewsAdmin/',
           views.AllViewsAdmin.as_view(),
           name= 'viewsAdmin'
     ),
     path('updeteFormulario/<pk>', 
         views.formularioUpdateView.as_view(),
         name= 'update'
    ),
     path('deleteEmpleado/<pk>', 
         views.empleadoDeleteView.as_view(),
         name= 'delete'
    ),
     path('crear-usuario/',
           views.EmpleadoCreateView.as_view(),
           name='CrearUsuario'
     ),

#----------------- URLS DE PRUEBAS --------------------------------------------------------------------------------------------------------------
    
    
    path('buscar-empleado/', views.byKword.as_view()),
    path('buscar-habilidades/', views.findByHabilidades.as_view()),
   
    path('succes/', 
         views.successTemplate.as_view(),
         name= 'correcto'
    ),
 
   
]

empleado/empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('', include('applications.departamento.urls')),
    path('', include('applications.prueba.urls')),
    path('', include('applications.persona.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

empleado/templates/includes/header.html
<div class="top-bar">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>
        <li><a href="{% url 'persona_app:inicio' %}" class="menu-text">Empleados</a></li>
        <li><a href="{% url 'persona_app:listarEmpleados' %}">Listar</a></li>
        <li><a href="{% url 'departamento_app:ListarDepartamentos' %}">Departamentos</a></li>
        <li><a href="{% url 'persona_app:viewsAdmin' %}">Administrar</a></li>
        <li><a href="{% url 'departamento_app:addDepartamento' %}">Nuevo Departamento</a></li>
      </ul>
    </div>
    <div class="top-bar-right">
      <ul class="menu">
        <li><input type="search" placeholder="Buscar"></li>
        <li><a href="{% url 'persona_app:CrearUsuario' %}" class="button">Registrar Nuevo</a></li>
      </ul>
    </div>
  </div>