empleado/applications/persona/urls.py
from django.urls import path
from . import views

app_name = 'persona_app'


urlpatterns = [
 #----------------- URLS DE MI PRIMER PROYECTO --------------------------------------------------------------------------------------------------------------   
     path('/', 
         views.inicio.as_view(),
         name= 'inicio'
    ),
     path('allViews/',
           views.AllViews.as_view(),
           name= 'listarEmpleados'
     ),
     path('detalles_empleado/<int:pk>',
           views.DetailViewEmpleado.as_view(),
           name= 'detalles_empleado'
     ),
     path('AllViewsByArea/<shortName>/', 
          views.AllViewsByArea.as_view(),
          name='EmpleadosPorArea'
     ),
     path('allViewsAdmin/',
           views.AllViewsAdmin.as_view(),
           name= 'viewsAdmin'
     ),
     path('updeteFormulario/<pk>', 
         views.formularioUpdateView.as_view(),
         name= 'update'
    ),
     path('deleteEmpleado/<pk>', 
         views.empleadoDeleteView.as_view(),
         name= 'delete'
    ),
     path('crear-usuario/',
           views.EmpleadoCreateView.as_view(),
           name='CrearUsuario'
     ),

#----------------- URLS DE PRUEBAS --------------------------------------------------------------------------------------------------------------
    
    
    path('buscar-empleado/', views.byKword.as_view()),
    path('buscar-habilidades/', views.findByHabilidades.as_view()),
   
    path('succes/', 
         views.successTemplate.as_view(),
         name= 'correcto'
    ),
 
   
]

empleado/empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('', include('applications.departamento.urls')),
    path('', include('applications.prueba.urls')),
    path('', include('applications.persona.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

empleado/applications/persona/models.py
from django.db import models
from applications.departamento.models import departamento

# Create your models here.

class habilidades(models.Model):
    habilidades = models.CharField("Habilidad", max_length=50)
    
    class Meta:
        verbose_name= 'habilidad'
        verbose_name_plural = 'Habilidades Empleado'
    
    def __str__(self):
        return self.habilidades 

class Empleado (models.Model):
    """Modelo para tabla empleado"""

    JOB_CHOICES = (
        ('0','CONTADOR'),
        ('1','ADMINISTRADOR'),
        ('2','ECONOMISTA'),
        ('0','OTRO'),
    )

    first_name = models.CharField("nombre", max_length=50)
    last_name = models.CharField("apellidos", max_length=50)
    full_name = models.CharField("nombre_completo", max_length=100, blank=True)
    job = models.CharField("trabajo", max_length=1, choices=JOB_CHOICES)
    departamento = models.ForeignKey(departamento, on_delete=models.CASCADE)
    imagen = models.ImageField("imagen", upload_to=None, height_field=None, width_field=None, max_length=None, null=True)
    habilidades = models.ManyToManyField(habilidades)

    def __str__(self):
        return str(self.id) + "-" + self.first_name + "-" + self.last_name

empleado/applications/persona/forms.py
from django import forms
from .models import Empleado

class EmpleadoForm(forms.ModelForm):

    class Meta:
        model = Empleado
        fields = ('first_name',
                  'last_name',
                  'job',
                  'departamento',
                  'imagen',
                  'habilidades',
            )
        widgets = {
            'habilidades': forms.CheckboxSelectMultiple()
        }

empleado/applications/persona/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.forms import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import ListView, CreateView, TemplateView, UpdateView, DeleteView, DetailView
from .models import Empleado
from django.urls import reverse_lazy
#formularios
from .forms import EmpleadoForm

# Create your views here.
#----------------- VIEWS DE MI PRIMER PROYECTO --------------------------------------------------------------------------------------------------------------


class inicio(TemplateView):
    template_name = "inicio.html"

class AllViews(ListView):
    model = Empleado
    template_name = "persona/List_all.html"
    paginate_by = 8
    def get_queryset(self):

        palabraClave = self.request.GET.get('kword','')
        empleado = Empleado.objects.filter(
            full_name__icontains = palabraClave
        )
        return empleado
    

class DetailViewEmpleado(DetailView):
    model = Empleado
    template_name = "persona/detailEmpleado.html"

class AllViewsByArea(ListView):
    model = Empleado
    template_name = "persona/byArea.html"
    paginate_by = 8
    def get_queryset(self):
        area = self.kwargs['shortName']
        lista = Empleado.objects.filter(departamento__short_name = area)
        return lista 

class AllViewsAdmin(ListView):
    model = Empleado
    template_name = "persona/List_all_admin.html"
    paginate_by = 8
    def get_queryset(self):

        palabraClave = self.request.GET.get('kword','')
        empleado = Empleado.objects.filter(
            full_name__icontains = palabraClave
        )
        return empleado
    
class formularioUpdateView(UpdateView):
    model = Empleado
    template_name = "persona/formularioUpdate.html"
    fields = ['first_name',
              'last_name',
              'job',
              'departamento',
              'habilidades',
              'imagen',
    ]
    success_url = reverse_lazy('persona_app:viewsAdmin')



class empleadoDeleteView(DeleteView):
    model = Empleado
    template_name = "persona/deleteEmpleado.html"
    success_url = reverse_lazy('persona_app:viewsAdmin')
    context_object_name = 'empleado'

class EmpleadoCreateView(CreateView):
    model = Empleado
    template_name = "persona/CreateEmpleado.html"
    form_class = EmpleadoForm
    success_url = reverse_lazy('persona_app:listarEmpleados')
    
    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        empleado = form.save( commit=False )  #guarda el formulario en una variable y el commit false es para hacer un simulado del guardado en vez de guardarlo de verdad para optimizar el programa
        empleado.full_name = empleado.first_name + ' ' + empleado.last_name
        empleado.save()

        return super(EmpleadoCreateView, self).form_valid(form)
    
    
    





#----------------- VIEWS DE PRUEBAS --------------------------------------------------------------------------------------------------------------


    

class byKword(ListView): 
    template_name = "persona/byKword.html"
    context_object_name = 'empleados'
    
    def get_queryset(self):
        palabraClave = self.request.GET.get('kword')
        empleado = Empleado.objects.filter(
            first_name = palabraClave
        )
        return empleado


class findByHabilidades(ListView):
    template_name = "persona/porHabilidades.html"
    context_object_name = 'habilidades'
    
    def get_queryset(self):
        empleadoId = Empleado.objects.get(id=1)
        return empleadoId.habilidades.all()




    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        empleado = form.save( commit=False )  #guarda el formulario en una variable y el commit false es para hacer un simulado del guardado en vez de guardarlo de verdad para optimizar el programa
        empleado.full_name = empleado.first_name + '' + empleado.last_name
        empleado.save()

        return super(EmpleadoCreateView, self).form_valid(form)

class successTemplate (TemplateView):
    template_name = "persona/success.html"

empleado/templates/persona/CreateEmpleado.html
{% extends 'base.html' %}

{% block content %} 

{% include 'includes/header.html' %}  
   
   
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell"> Crear Nuevo Empleado</h1>
        <form class="grid-margin-x grid-x" method="post" enctype="multipart/form-data">{% csrf_token %}
            <div class="medium-6 cell">
                <label><b> Nombre:</b>
                    {{form.first_name}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label> <b> Apellido:</b>
                    {{form.last_name}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label> <b> Trabajo:</b>
                    {{form.job}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label> <b> Departamento:</b>
                    {{form.departamento}}
                </label>
            </div>
            <div class="large-6 cell ">
                <label> <b> Habilidades:</b>
                    {{form.habilidades}}
                </label>
            </div>
            <div class="large-6 cell ">
                <label> <b> Foto De Perfil:</b>
                    {{form.imagen}}
                </label>
            </div>

            
            <button  type="submit" class="button cell large-2 ">Guadar</button>
        </form>
    </div>
   

</div> 
   
{% endblock content %}

   

empleado/templates/persona/List_all.html
{% extends 'base.html' %}

{% block content %} 

{% include 'includes/header.html' %}

<div class="grid-container">
    <h1>Lista Empleados</h1>
        <!--Input y buscador-->
    <form method="get"  class="grid-x grid-margin-x"> {% csrf_token %}
        <div class="cell large-6">  <input type="text" name="kword" id="kword" placeholder="Nombre Empleado"></div>
        <div class="cell large-4">  <button class="button" type="sumbit">Buscar</button> </div>
    </form>
    <div> 
        <!--Creador de tabla-->
        <table>
            <thead>
              <tr>
                <th width="150">ID</th>
                <th width="150">NOMBRES</th>
                <th width="150">APELLIDOS</th>
                <th width="150">DEPARTAMENTO</th>
                <th width="150">ACCION</th>
              </tr>
            </thead>
            <tbody>
            {% for empleado in object_list %}
              <tr>
                <td>{{empleado.id}}</td>
                <td>{{empleado.first_name|upper}}</td>
                <td>{{empleado.last_name|upper}}</td>
                <td>{{empleado.departamento|upper}}</td>
                <td><a href="{% url 'persona_app:detalles_empleado' empleado.id %}" class="button">Ver</a></td>
              </tr>
            {% endfor %}
            </tbody>
        </table>
        <!--Paginacion-->
        <div class="pagination-centered">
            <ul class="pagination" role="navigation" aria-label="Pagination">
                {% if page_obj.has_previous %}
                    <li class="pagination-previous"><a href="?page=1">&laquo; Primera</a></li>
                    <li class="pagination-previous"><a href="?page={{ page_obj.previous_page_number }}">Anterior</a></li>
                {% else %}
                    <li class="pagination-previous disabled">Primera</li>
                    <li class="pagination-previous disabled">Anterior</li>
                {% endif %}

                {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                        <li class="current"><span>{{ num }}</span></li>
                    {% elif num > page_obj.number|add:-3 and num < page_obj.number|add:3 %}
                        <li><a href="?page={{ num }}">{{ num }}</a></li>
                    {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                    <li class="pagination-next"><a href="?page={{ page_obj.next_page_number }}">Siguiente</a></li>
                    <li class="pagination-next"><a href="?page={{ page_obj.paginator.num_pages }}">Ultima &raquo;</a></li>
                {% else %}
                    <li class="pagination-next disabled">Siguiente</li>
                    <li class="pagination-next disabled">Ultima</li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>

    
{% endblock content %}

empleado/templates/persona/List_all_admin.html
{% extends 'base.html' %}

{% block content %} 

{% include 'includes/header.html' %}

<div class="grid-container">
    <h1>Adminisitrar Empleados</h1>
        <!--Input y buscador-->
    <form method="get"  class="grid-x grid-margin-x"> {% csrf_token %}
        <div class="cell large-6">  <input type="text" name="kword" id="kword" placeholder="Nombre Empleado"></div>
        <div class="cell large-4">  <button class="button" type="sumbit">Buscar</button> </div>
    </form>
    <div> 
        <!--Creador de tabla-->
        <table>
            <thead>
              <tr>
                <th width="200">ID</th>
                <th width="200">NOMBRES</th>
                <th width="200">APELLIDOS</th>
                <th width="200">DEPARTAMENTO</th>
                <th width="200">ACCION</th>
              </tr>
            </thead>
            <tbody>
            {% for empleado in object_list %}
              <tr>
                <td>{{empleado.id}}</td>
                <td>{{empleado.first_name|upper}}</td>
                <td>{{empleado.last_name|upper}}</td>
                <td>{{empleado.departamento|upper}}</td>
                <td><a href="{% url 'persona_app:update' empleado.id %}" class="button">editar</a></td>
                <td><a href="{% url 'persona_app:delete' empleado.id %}" class="button alert">eliminar</a></td>
              </tr>
            {% endfor %}
            </tbody>
        </table>
        <!--Paginacion-->
        <div class="pagination-centered">
            <ul class="pagination" role="navigation" aria-label="Pagination">
                {% if page_obj.has_previous %}
                    <li class="pagination-previous"><a href="?page=1">&laquo; Primera</a></li>
                    <li class="pagination-previous"><a href="?page={{ page_obj.previous_page_number }}">Anterior</a></li>
                {% else %}
                    <li class="pagination-previous disabled">Primera</li>
                    <li class="pagination-previous disabled">Anterior</li>
                {% endif %}

                {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                        <li class="current"><span>{{ num }}</span></li>
                    {% elif num > page_obj.number|add:-3 and num < page_obj.number|add:3 %}
                        <li><a href="?page={{ num }}">{{ num }}</a></li>
                    {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                    <li class="pagination-next"><a href="?page={{ page_obj.next_page_number }}">Siguiente</a></li>
                    <li class="pagination-next"><a href="?page={{ page_obj.paginator.num_pages }}">Ultima &raquo;</a></li>
                {% else %}
                    <li class="pagination-next disabled">Siguiente</li>
                    <li class="pagination-next disabled">Ultima</li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>

    
{% endblock content %}

empleado/templates/persona/byArea.html
{% extends 'base.html' %}

{% block content %} 

{% include 'includes/header.html' %}

<div class="grid-container">
    <h1>Lista Empleados</h1>
    <div> 
        <!--Creador de tabla-->
        <table>
            <thead>
              <tr>
                <th width="150">ID</th>
                <th width="150">NOMBRES</th>
                <th width="150">APELLIDOS</th>
                <th width="150">DEPARTAMENTO</th>
                <th width="150">ACCION</th>
              </tr>
            </thead>
            <tbody>
            {% for empleado in object_list %}
              <tr>
                <td>{{empleado.id}}</td>
                <td>{{empleado.first_name|upper}}</td>
                <td>{{empleado.last_name|upper}}</td>
                <td>{{empleado.departamento|upper}}</td>
                <td><a href="{% url 'persona_app:detalles_empleado' empleado.id %}" class="button">Ver</a></td>
              </tr>
            {% endfor %}
            </tbody>
        </table>
        <!--Paginacion-->
        <div class="pagination-centered">
            <ul class="pagination" role="navigation" aria-label="Pagination">
                {% if page_obj.has_previous %}
                    <li class="pagination-previous"><a href="?page=1">&laquo; Primera</a></li>
                    <li class="pagination-previous"><a href="?page={{ page_obj.previous_page_number }}">Anterior</a></li>
                {% else %}
                    <li class="pagination-previous disabled">Primera</li>
                    <li class="pagination-previous disabled">Anterior</li>
                {% endif %}

                {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                        <li class="current"><span>{{ num }}</span></li>
                    {% elif num > page_obj.number|add:-3 and num < page_obj.number|add:3 %}
                        <li><a href="?page={{ num }}">{{ num }}</a></li>
                    {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                    <li class="pagination-next"><a href="?page={{ page_obj.next_page_number }}">Siguiente</a></li>
                    <li class="pagination-next"><a href="?page={{ page_obj.paginator.num_pages }}">Ultima &raquo;</a></li>
                {% else %}
                    <li class="pagination-next disabled">Siguiente</li>
                    <li class="pagination-next disabled">Ultima</li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>

    
{% endblock content %}

empleado/templates/persona/byKword.html
<h1>BUSCAR EMPLEADOS</h1>
<form method="GET">{% csrf_token %}
    <input type="text" id="kword" name="kword" placeholder="Ingrese un nombre"> </input>
    <button type="submit">Buscar</button>
</form>

<h3> lista empleados:</h3>

<ul>
    
        
        {% for e in empleados%}
        <li>{{e}}</li>  
        {% endfor %}
            
    
</ul>
    

empleado/templates/persona/deleteEmpleado.html
{% extends 'base.html' %}

{% block content %} 

{% include 'includes/header.html' %}  
   
   
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell"> Eliminar Empleado: {{empleado.first_name}}</h1>
    <form method="post">{% csrf_token %}
        <div class="callout alert">
            <h5>Seguro que desea eliminar al empleado?</h5>
            <p>Si pones confirmar se borraran todos sus datos para siempre.</p>
          </div>
        <button class="alert button" type="submit">Confirmar</button>
    </form>
    </div>
   

</div> 
   
{% endblock content %}

   

empleado/templates/persona/detailEmpleado.html
{% extends 'base.html' %}
{% load static %}

{% block tittle %}
    {{object.full_name}}
{% endblock tittle %}
    
{% block content %} 

{% include 'includes/header.html' %}  
   
   
<div class="grid-container" style="margin-top: 30px;">
    <div class="grid-x grid-margin-x align-center ">
        <div class="card cell large-4" style="width: 300px;">
            <div class="card-divider">
              {{empleado.get_job_display}}
            </div>
            
            {% if empleado.imagen %}
                <img src="{{ empleado.imagen.url }}">
            {% else %}
                <img src="{% static 'img/notFound.jpg'%}" alt="imagen">
            {% endif %}
                
            
            <div class="card-section">
                <h4>{{empleado.full_name}}</h4>
                <p><b>Nombre:</b> {{empleado.first_name}}</p>
                <p><b>Apellido:</b> {{empleado.last_name}}</p>
                <p><b>Departamento:</b> {{empleado.departamento.name}}</p>
                <p><span class="label">Habilidades y Atributos:</span></p>
                <ul class="vertical menu"></ul>
                    {% for h in empleado.habilidades.all %}
                        <li> {{h.habilidades}}</li>
                    {% endfor %}
                <td><a href="{% url 'persona_app:delete' empleado.id %}" style="margin-top: 10px;" class="button alert">Eliminar Empleado</a></td>
                    
            </div>
          </div>
    </div>
   

</div> 

{% endblock content %}

   

empleado/templates/persona/formularioUpdate.html
{% extends 'base.html' %}

{% block content %} 

{% include 'includes/header.html' %}  
   
   
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell"> Actualizar Empleado</h1>
        <form class="grid-margin-x grid-x" method="post">{% csrf_token %}
            <div class="medium-6 cell">
                <label> Nombre:
                    {{form.first_name}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label> Apellido:
                    {{form.last_name}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label> Trabajo:
                    {{form.job}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label> Departamento:
                    {{form.departamento}}
                </label>
            </div>
            <div class="large-6 cell ">
                <label> Habilidades:
                    {{form.habilidades}}
                </label>
            </div>
            <div class="large-6 cell ">
                <label> Foto De Perfil:
                    {{form.imagen}}
                </label>
            </div>
            <div class="large-6 cell">
            
            </div>
            
            <button  type="submit" class="button cell large-2 ">Guadar</button>
        </form>
    </div>
   

</div> 
   
{% endblock content %}

   
   
   
   

empleado/templates/persona/porHabilidades.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=>, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Lista de habilidades por empleado</h1>
   
    <ul>
        {% for h in habilidades %}
            <li>{{h}}</li>
        {% endfor %}
    </ul>

    
        
</body>
</html>

empleado/templates/persona/success.html
<h1>Empleado cargado correctamente!</h1>