empleado/applications/departamento/urls.py
from django.urls import path, include
from . import views

app_name = 'departamento_app'
urlpatterns = [
    #----------------- URLS DE MI PRIMER PROYECTO --------------------------------------------------------------------------------------------------------------   
    path('', 
        views.DepartamentosListView.as_view(),
        name= 'ListarDepartamentos'
    ),
    path('agregarDepartamento/',
          views.departamentoFormView.as_view(),
            name= 'addDepartamento' ),
    
    #----------------- URLS DE PRUEBAS --------------------------------------------------------------------------------------------------------------
    path('index/', views.indexView.as_view() ),
    
]

empleado/applications/persona/urls.py
from django.urls import path
from . import views

app_name = 'persona_app'


urlpatterns = [
 #----------------- URLS DE MI PRIMER PROYECTO --------------------------------------------------------------------------------------------------------------   
     path('/', 
         views.inicio.as_view(),
         name= 'inicio'
    ),
     path('allViews/',
           views.AllViews.as_view(),
           name= 'listarEmpleados'
     ),
     path('detalles_empleado/<int:pk>',
           views.DetailViewEmpleado.as_view(),
           name= 'detalles_empleado'
     ),
     path('AllViewsByArea/<shortName>/', 
          views.AllViewsByArea.as_view(),
          name='EmpleadosPorArea'
     ),
     path('allViewsAdmin/',
           views.AllViewsAdmin.as_view(),
           name= 'viewsAdmin'
     ),
     path('updeteFormulario/<pk>', 
         views.formularioUpdateView.as_view(),
         name= 'update'
    ),
     path('deleteEmpleado/<pk>', 
         views.empleadoDeleteView.as_view(),
         name= 'delete'
    ),
     path('crear-usuario/',
           views.EmpleadoCreateView.as_view(),
           name='CrearUsuario'
     ),

#----------------- URLS DE PRUEBAS --------------------------------------------------------------------------------------------------------------
    
    
    path('buscar-empleado/', views.byKword.as_view()),
    path('buscar-habilidades/', views.findByHabilidades.as_view()),
   
    path('succes/', 
         views.successTemplate.as_view(),
         name= 'correcto'
    ),
 
   
]

empleado/empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('', include('applications.departamento.urls')),
    path('', include('applications.prueba.urls')),
    path('', include('applications.persona.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

empleado/applications/departamento/models.py
from django.db import models

# Create your models here.

class departamento (models.Model):
    name = models.CharField("nombre", max_length=50, unique=True)
    short_name = models.CharField("nombre corto", max_length=50, unique=True)
    active = models.BooleanField("activo", default=False)

    def __str__(self):
        return str(self.id) + "-" + self.name + "-" + self.short_name

empleado/applications/departamento/forms.py
from django import forms

class newDepartament (forms.Form):
    nombre = forms.CharField( max_length=50)
    apellido = forms.CharField( max_length=50)
    departamento = forms.CharField( max_length=50)
    shorName = forms.CharField( max_length=50)

empleado/applications/departamento/views.py
from django.forms import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import TemplateView,CreateView,ListView
from django.views.generic.edit import FormView
from django.urls import reverse_lazy
from .forms import newDepartament
from .models import departamento
from applications.persona.models import Empleado
# Create your views here.
#----------------- VIEWS DE MI PRIMER PROYECTO --------------------------------------------------------------------------------------------------------------
class DepartamentosListView(ListView):
    model = departamento
    template_name = "departamento/listAllDepartamentos.html"

class departamentoFormView(FormView):     #Form view es una vista que simula un formulario que puede servir para hacer un createView con mas de un modelo
    template_name = "departamento/addDepartamento.html"
    form_class = newDepartament
    success_url = reverse_lazy('departamento_app:ListarDepartamentos')



    def form_valid(self, form: BaseModelForm) -> HttpResponse:

        depa = departamento(                  #aca llamamos el modelo departamento y le asignamos un campo del formulario creado en forms.py
            name= form.cleaned_data['departamento'],
            short_name= form.cleaned_data['shorName']
        )       
        depa.save()    #aca guardamos la variable depa en la base de datos para que podamos hacer la relacion con el empleado 
        
        nombre = form.cleaned_data['nombre']     #aca asignamos de nuevo el nombre y apellido del empleado en una variable
        apellido = form.cleaned_data['apellido']
        Empleado.objects.create(              #aca hacemos la relacion del forms y la conectamos con el modelo de persona y de departamento
            first_name = nombre,
            last_name = apellido,
            job = '1',
            departamento = depa
        )
        

        return super(departamentoFormView, self).form_valid(form)


#----------------- VIEWS DE PRUEBAS --------------------------------------------------------------------------------------------------------------
class indexView(TemplateView):
    template_name = "departamento/index.html"

empleado/templates/departamento/addDepartamento.html
{% extends 'base.html' %}

{% block content %} 

{% include 'includes/header.html' %}  
   
   
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell"> Agregar Nuevo Departamento</h1>
        <form class="grid-margin-x grid-x" method="post">{% csrf_token %}
            <h3 class="medium-12 cell"> Empleado a Cargo:</h3>
            <div class="medium-6 cell">
                <label> Nombre:
                    {{form.nombre}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label> Apellido:
                    {{form.apellido}}
                </label>
            </div>
            <h3 class="medium-12 cell"> Nuevo Departamento:</h3>
            <div class="medium-6 cell">
                <label> Nombre Departamento:
                    {{form.departamento}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label> Nombre corto:
                    {{form.shorName}}
                </label>
            </div>
            <button  type="submit" class="button cell large-2 ">Agregar</button>
        </form>
    </div>
   

</div> 
   
{% endblock content %}

empleado/templates/departamento/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto pariatur expedita odit aliquid praesentium odio! Facilis, voluptatum. Maiores porro qui delectus, aut inventore, ex deleniti voluptatibus ipsam quos, sed nesciunt.</h1>
</body>
</html>

empleado/templates/departamento/listAllDepartamentos.html
{% extends 'base.html' %}

{% block content %} 

{% include 'includes/header.html' %}
<div class="grid-container">
    <h1 class="large-4">Departamentos</h1> 
    <div> 
        <!--Creador de tabla-->
        <table>
            <thead>
              <tr>
                <th width="150">NOMBRES</th>
                <th width="150">DEPARTAMENTO</th>
                <th width="150">ACCION</th>
              </tr>
            </thead>
            <tbody>
            {% for area in object_list %}
              <tr>
                <td>{{area.name|upper}}</td>
                <td>{{area.short_name|upper}}</td>
                <td><a href="{% url 'persona_app:EmpleadosPorArea' area.short_name %}" class="button">Ver Empleados</a></td>
              </tr>
            {% endfor %}
            </tbody>
        </table>
        <!--Paginacion-->
    </div>
</div>

    
{% endblock content %}